name: Release Privado CLI

on:
  push:
    tags: ["*"]

jobs:
  check-release-condition:
    name: Check release criteria
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.checkRelease.outputs.makeRelease }}
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo ${{ github.sha }}
      - id: checkRelease
        run: |
          ALLOWED_BRANCHES=( "main" "master" "feat/actions" )

          # set default output
          echo "::set-output name=makeRelease::false"

          for branch in "${ALLOWED_BRANCHES[@]}"
          do
            echo  "Loop step: ${{ github.sha }} $(git rev-parse origin/$branch)"
            if [[ ${{ github.sha }} == $(git rev-parse origin/$branch) ]]
            then
              echo "::set-output name=makeRelease::true"
              break
            fi
          done
  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: check-release-condition
    if: ${{ needs.check-release-condition.outputs.release == 'true' }}
    outputs:
      tag: ${{ steps.settag.outputs.tag }}
      # makeRelease: ${{ steps.settag.outputs.release }}
    steps:
      - uses: actions/checkout@v2

      - name: Set release tag
        id: settag
        run: |
          echo ${{ needs.check-release-condition.outputs.release }}
          PRIVADO_RELEASE_TAG=$GITHUB_REF_NAME
          if [[ $PRIVADO_RELEASE_TAG = "latest" ]] 
          then
            PRIVADO_RELEASE_TAG=$(git describe --tags --abbrev=0)
          fi
          echo "Final Tag: $PRIVADO_RELEASE_TAG"

          echo "PRIVADO_RELEASE_TAG=$(echo -n $PRIVADO_RELEASE_TAG)" >> $GITHUB_ENV
          echo "::set-output name=tag::$PRIVADO_RELEASE_TAG"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PRIVADO_RELEASE_TAG }}
          release_name: Privado CLI ${{ env.PRIVADO_RELEASE_TAG }}
          draft: false
          prerelease: false



  release-assets:
    name: Attach Release Assets
    runs-on: ubuntu-20.04
    needs: release
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
      
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.24
        with:
          release_tag: ${{ needs.release.outputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "privado"
          goversion: "https://dl.google.com/go/go1.18.4.linux-amd64.tar.gz"
          extra_files: README.md
          asset_name: privado-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
          ldflags: "-X 'github.com/Privado-Inc/privado-cli/cmd.Version=${{ needs.release.outputs.tag }}'"
