name: Release TBB binaries

on:
  release:
    types: [created, edited]

jobs:
  set-release-tag:
    name: Set Release Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.settag.outputs.tag }}
    steps:
      - name: Set release tag
        id: settag
        run: |
          PRIVADO_RELEASE_TAG=$GITHUB_REF_NAME
          if [[ $PRIVADO_RELEASE_TAG = "latest" ]] 
          then
            PRIVADO_RELEASE_TAG=$(curl --silent "https://api.github.com/repos/Privado-Inc/privado/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          fi
          echo "Final Tag: $PRIVADO_RELEASE_TAG"
          echo "::set-output name=tag::$PRIVADO_RELEASE_TAG"

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: set-release-tag
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
      
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "privado"
          goversion: "https://dl.google.com/go/go1.17.6.linux-amd64.tar.gz"
          extra_files: README.md
          asset_name: privado-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
          ldflags: "-X 'github.com/Privado-Inc/privado-cli/cmd.Version=${{ needs.set-release-tag.outputs.tag }}'"
