name: Release Privado CLI

on:
  push:
    branches: [master, main, feat/actions]
    tags: ["*"]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.settag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set release tag
        id: settag
        run: |
          PRIVADO_RELEASE_TAG=$GITHUB_REF_NAME
          if [[ $PRIVADO_RELEASE_TAG = "latest" ]] 
          then
            PRIVADO_RELEASE_TAG=$(git describe --tags --abbrev=0)
          fi
          echo "Final Tag: $PRIVADO_RELEASE_TAG"
          echo "PRIVADO_RELEASE_TAG=$(echo -n $PRIVADO_RELEASE_TAG)" >> $GITHUB_ENV
          echo "::set-output name=tag::$PRIVADO_RELEASE_TAG"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PRIVADO_RELEASE_TAG }}
          release_name: Privado CLI ${{ env.PRIVADO_RELEASE_TAG }}
          draft: false
          prerelease: false



  release-assets:
    name: Attach Release Assets
    runs-on: ubuntu-20.04
    needs: release
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
      
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.24
        with:
          release_tag: ${{ needs.release.outputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "privado"
          goversion: "https://dl.google.com/go/go1.18.4.linux-amd64.tar.gz"
          extra_files: README.md
          asset_name: privado-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
          ldflags: "-X 'github.com/Privado-Inc/privado-cli/cmd.Version=${{ needs.release.outputs.tag }}'"
